import CheckData from './APIs/CheckData';
import EditBusiness from './APIs/EditBusiness';
import SendPictureMessage from './APIs/MessagePicture';
import NewBusiness from './APIs/NewBusiness';
import NewBusinessUser from './APIs/NewBusinessUser';
import NewSellsPoint from './APIs/NewSellsPoint';
import Signup from './APIs/Signup';
import SocketMessage from './APIs/Socket';
import UploadProfilePicture from './APIs/UploadProfilePicture';
import UploadVoiceNote from './APIs/UploadVoiceNote';
import EditSalesPoint from './APIs/EditSalesPoint';
import EditBusinessUser from './APIs/EditBusinessUser';

Signup();
SocketMessage();
// SendPresavedMessages();
// FindUserMessages();
EditBusinessUser();
EditSalesPoint();
CheckData();
NewBusinessUser();
UploadProfilePicture();
NewSellsPoint();
NewBusiness();
UploadVoiceNote();
SendPictureMessage();
EditBusiness();
