import SendPictureMessage from './APIs/MessagePicture';
import NewBusiness from './APIs/NewBusiness';
import NewBusinessUser from './APIs/NewBusinessUser';
import NewSellsPoint from './APIs/NewSellsPoint';
import Signup from './APIs/Signup';
import SocketMessage from './APIs/Socket';
import UploadProfilePicture from './APIs/UploadProfilePicture';
import UploadVoiceNote from './APIs/UploadVoiceNote';

Signup();
SocketMessage();
// SendPresavedMessages();
// FindUserMessages();
// SetChatRead();
// SetMessagesReceived();
// FindStatusMessages();
NewBusinessUser();
UploadProfilePicture();
NewSellsPoint();
NewBusiness();
UploadVoiceNote();
SendPictureMessage();
// FetchUserData();
